### ISSUE TITLE
'for' limit must be a number

### ISSUE THREAD

**Issue by BBLJB** [jevajs/Jeva#5]
Not sure what's wrong

**Comment by ThatZiv** [comment]
What is the issue? what resource and what line is this happening. Please be more specific.

**Comment by Boomatisch** [comment]
Hello! I want to use your writen "war" Command and i got this Error: 'for' limit must be a number

Any Help?

**Comment by x0Z3ro0x** [comment]
Show me the error you get, and the code to the command and I will try to help you the best I can :)
