### ISSUE TITLE
/on and /off dont work

### ISSUE THREAD

**Issue by WantToLearnCoding** [jevajs/Jeva#6]
Hey Jeva, I like you work a lot. I just wanna ask why my /on and /off is not working to make the banner dissappear. I copied your script that you post. Is there an update about it to make the script run?

**Comment by CristianoTRS** [comment]
Hi @WantToLearnCoding !

Could you please send a screenshot of what you have done? Thanks!

Cristiano.

**Comment by WantToLearnCoding** [comment]
I already got it Fixed. Thank You for being active support! ^^

**Comment by Im-JJ** [comment]
I have the same problem could you share how you fixed it?

**Comment by ThatZiv** [comment]
What does your console output when you trigger the /on
