### ISSUE TITLE
issue with discordbot starting

### ISSUE THREAD

**Issue by wil2005-development** [jevajs/Jeva#7]
Hello,

I start discordbotfivem. But i have a error
SCRIPT ERROR in timer: Error [ERR_UNHANDLED_ERROR]: Unhandled error. ([object Object])
> Client.emit (events.js:199)
> WebSocketShard.onError (/home/container/resources/[ESX]/[extensions]/discordbot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:330)
> WebSocket.onError (/home/container/resources/[ESX]/[extensions]/discordbot/node_modules/ws/lib/event-target.js:128)
> WebSocket.emit (events.js:210)
> abortHandshake (/home/container/resources/[ESX]/[extensions]/discordbot/node_modules/ws/lib/websocket.js:718)
> WebSocket.close (/home/container/resources/[ESX]/[extensions]/discordbot/node_modules/ws/lib/websocket.js:217)
> WebSocketShard.destroy (/home/container/resources/[ESX]/[extensions]/discordbot/node_modules/discord.js/src/client/websocket/WebSocketShard.js:498)
> WebSocketManager.destroy (/home/container/resources/[ESX]/[extensions]/discordbot/node_modules/discord.js/src/client/websocket/WebSocketManager.js:279)
> Client.destroy (/home/container/resources/[ESX]/[extensions]/discordbot/node_modules/discord.js/src/client/Client.js:276)
> (/home/container/resources/[ESX]/[extensions]/discordbot/node_modules/discord.js/src/client/Client.js:260)

what is my problemen and have you a fix for this

**Comment by ThatZiv** [comment]
What does your `package.json` file look like?

**Comment by wil2005-development** [comment]
{
  "name": "fivem_discord_bot",
  "version": "1.0.0",
  "description": "",
  "main": "bot.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "discord.js": "github:vecchiotom/discord.js"
  }
}

This is the package,json file.

**Comment by wil2005-development** [comment]
i fix the issue, its was my fault xD, but thanks for your help
