### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rudygamer1990** [jevajs/Jeva#8]
UnhandledPromiseRejectionWarning: ReferenceError: GetNumPlayerIndices is not defined

**Comment by ThatZiv** [comment]
What does the directory, package.json, and the file itself look like?

**Comment by metzos** [comment]
UnhandledPromiseRejectionWarning: ReferenceError: GetNumPlayerIndices is not defined

**Comment by wil2005-development** [comment]
Please let see your package.json otherwise we cannot help you.

**Comment by Donnnnnnnnnnnnn** [comment]
UnhandledPromiseRejectionWarning: ReferenceError: GetNumPlayerIndices is not defined 

please help :( 

![image](https://user-images.githubusercontent.com/63995599/98616350-35eb9a00-232f-11eb-9010-6f9ada4c4be9.png)

**Comment by ThatZiv** [comment]
You **must** run this version of the bot through fxserver, not through node via command line.
